freshmen_world/WOF/urls.py
from django.urls import path
from WOF import views

app_name = 'WOF'

urlpatterns = [
	path('', views.index, name='index'),
	path('login/', views.user_login, name='user_login'),
	path('register/', views.user_register, name='user_register'),
	path('selector/', views.selector, name='selector'),
	path('selector/add_university', views.add_university, name='add_university'),
	path('selector/add_course/', views.add_course, name='add_course'),
	path('selector/course/<slug:course_name_slug>/delete_course', views.delete_course, name='delete_course'),
	path('selector/course/<slug:course_name_slug>/', views.show_course, name='show_course'),
	path('selector/course/<slug:course_name_slug>/uni_course_info.txt', views.get_course_info, name='get_course_info'),
	path('selector/university/<slug:university_name_slug>/', views.show_university, name='show_university'),
	path('taskmanager/', views.task_manager, name='task_manager'),
	path('taskmanager/add_task/', views.add_task, name="add_task"),
	path('taskmanager/server/', views.find_tasks_month, name='find_tasks'),
	path('logout/', views.user_logout, name='logout'),
	path('error/', views.error, name="error"),
	path('team/', views.team_members, name='team'),
	path('profile/', views.profile, name='profile'),
	path('profile/delete_university/', views.delete_university, name="delete_university"),
]

freshmen_world/freshmen_world/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from WOF import views


urlpatterns = [
    path('', views.index, name='index'),
    path('WOF/', include('WOF.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

freshmen_world/WOF/forms.py
from django import forms
from WOF.models import *
from django.contrib.auth.models import User


class StudentUserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('username', 'password', 'email')

		widgets = {
			'username' : forms.TextInput(attrs={'placeholder' : 'Username'}),
			'password' : forms.PasswordInput(attrs={'placeholder' : 'Password'}),
			'email' : forms.TextInput(attrs={'placeholder' : 'Email'}),
		}

		help_texts = {
			'username' : None,
			'password' : None,
			'email' : None,
		}

		labels = {
			'username' : "",
			'password' : "",
			'email' : "",
		}

	def __init__(self, *args, **kwargs):
		super(StudentUserForm, self).__init__(*args, **kwargs)
		self.fields['email'].required = False

class StudentUserProfileForm(forms.ModelForm):
	class Meta:
		model = StudentUser
		fields = ('university', 'degree', 'level', 'isAdmin')

		widgets = {
			'degree' : forms.TextInput(attrs={'placeholder' : 'Degree name', }),
			'level' : forms.NumberInput(attrs={'placeholder' : "University Year", 'min':1, 'max':10}),
			'isAdmin': forms.CheckboxInput(attrs={})
		}
	
		labels = {
			'university' : "",
			'degree' : "",
			'level' : "",
			'isAdmin': "Admin",
		}


	def __init__(self, *args, **kwargs):
		super(StudentUserProfileForm, self).__init__(*args, **kwargs)
		self.fields['university'].required = False
		self.fields['degree'].required = False
		self.fields['level'].required = False

class StudentUserChangeForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'password', 'email',)

		widgets = {
			'username' : forms.TextInput(attrs={'placeholder' : 'Username'}),
			'password' : forms.PasswordInput(attrs={'placeholder' : 'Password'}),
			'email' : forms.TextInput(attrs={'placeholder' : 'Email'}),
			'first_name' : forms.TextInput(attrs={'placeholder' : 'First name'}),
			'last_name' : forms.TextInput(attrs={'placeholder' : 'Last name'}),
		}

		help_texts = {
			'username' : None,
			'password' : None,
			'email' : None,
		}

		labels = {
			'username' : "",
			'password' : "",
			'email' : "",
			'first_name': "",
			'last_name': "",
		}

	def __init__(self, *args, **kwargs):
		super(StudentUserChangeForm, self).__init__(*args, **kwargs)
		# self.fields['email'].required = False
		self.fields['first_name'].required = False
		self.fields['last_name'].required = False

class StudentUserChangeProfileForm(forms.ModelForm):
	class Meta:
		model = StudentUser
		fields = ('university', 'degree', 'level', 'isAdmin')

		widgets = {
			'degree' : forms.TextInput(attrs={'placeholder' : 'Degree name', }),
			'level' : forms.NumberInput(attrs={'placeholder' : "University Year", 'value':"", 'min': '1','max':10}),
			'isAdmin': forms.CheckboxInput(attrs={}),
		}
	
		labels = {
			'university' : "",
			'degree' : "",
			'level' : "",
			'isAdmin': "Admin",
		}


	def __init__(self, *args, **kwargs):
		super(StudentUserChangeProfileForm, self).__init__(*args, **kwargs)
		self.fields['university'].required = False
		self.fields['degree'].required = False
		self.fields['level'].required = False

class CourseForm(forms.ModelForm):

	class Meta:
		model = Course
		fields = (
			'name', 'level', 'credits', 'courseConvener', 
			'courseNumber', 'university',
			)

		labels = {
			'name': "",
			'level': "",
			'credits': "",
			'courseConvener': "",
			'courseNumber': "",
			'university': "",
		}

		widgets = {
			'name':  forms.TextInput(attrs={'placeholder' : 'Course name'}),
			'level': forms.NumberInput(attrs={'placeholder' : 'Course Level'}),
			'credits': forms.NumberInput(attrs={'placeholder' : 'Credits'}),
			'courseConvener' : forms.TextInput(attrs={'placeholder' : 'Course Head'}),
			'courseNumber' : forms.TextInput(attrs={'placeholder' : 'Course Number'}),
		}

class UniversityForm(forms.ModelForm):
	class Meta:
		model = University
		fields = (
			'name',
			'location',
			)

		labels = {
			'name' : "",
			'location' : "",
		}

		widgets = {
			'name' : forms.TextInput(attrs={'placeholder' : "University Name"}),
			'location' : forms.TextInput(attrs={'placeholder' : "Location"}),
		}

freshmen_world/WOF/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.template.defaultfilters import slugify
from WOF.forms import *
from WOF.models import StudentUser, Course, University
from WOF.xmlWriter import writeCourseToXML, writeUniversityToXML
import xml.etree.ElementTree as ET, os, datetime as datetime

def index(request):
	context_dict = {}
	response = render(request, 'WOF/index.html', context=context_dict)
	return response

def team_members(request):
	return render(request, 'WOF/team_members.html', context={})

def selector(request):
	return redirect(reverse("WOF:index"))

@login_required
def profile(request):
	updated = False
	student_user_university = None
	if (StudentUser.objects.filter(user=request.user).exists()):
		student_user = StudentUser.objects.filter(user=request.user)[0]
		if student_user.university != None:
			student_user_university = student_user.university
	else:
		return redirect(reverse('WOF:index'))
	
	if request.method == "POST":
		student_user_change_form = StudentUserChangeForm(request.POST, instance=request.user)
		student_user_change_profile_form = StudentUserChangeProfileForm(request.POST, instance=student_user)

		if student_user_change_form.is_valid() and student_user_change_profile_form.is_valid():
			updated = True
			
			student_user = student_user_change_form.save()
			student_user.set_password(student_user.password)
			student_user.save()

			student_user_profile = student_user_change_profile_form.save()
			student_user_profile.user = student_user 
			student_user_profile.save()
			login(request, student_user)
		else:
			print(student_user_change_form.errors, student_user_change_profile_form.errors)
	else:
		student_user_change_form = StudentUserChangeForm(instance=request.user)
		student_user_change_profile_form = StudentUserChangeProfileForm(instance=student_user)
	return render(request, 'WOF/account.html', context={'student_user_change_form' : student_user_change_form,
														'student_user_change_profile_form' : student_user_change_profile_form,
														'student_user_university' : student_user_university,
														'updated' : updated})

def user_login(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(username=username, password=password)
		if user:
			if user.is_active:
				login(request, user)
				return redirect(reverse('WOF:index'))
			else:
				return HttpResponse("Account disabled")
		else:
			print(f"Invalid login details supplied: {username}, {password}")
			return HttpResponse("Invalid login details supplied")
	else:
		return render(request, 'WOF/user_login.html')
	return response

def user_register(request):
	registered = False

	if request.method == "POST":
		student_user_form = StudentUserForm(request.POST)
		student_user_profile_form = StudentUserProfileForm(request.POST)

		if student_user_form.is_valid() and student_user_profile_form.is_valid():
			student_user = student_user_form.save()
			student_user.set_password(student_user.password)
			student_user.save()

			profile = student_user_profile_form.save(commit=False)
			profile.user = student_user

			profile.save()

			registered = True
			login(request, student_user)
		else:
			print(student_user_form.errors, student_user_profile_form.errors)
	else:
		student_user_form = StudentUserForm()
		student_user_profile_form = StudentUserProfileForm()
	return render(request, 'WOF/user_register.html', context={'student_user_form': student_user_form, 
														'student_user_profile_form': student_user_profile_form,
															'registered': registered})

@login_required
def user_logout(request):
	logout(request)
	return redirect(reverse('WOF:index'))

@login_required
def show_course(request, course_name_slug):
	context_dict = {}
	try:
		course = Course.objects.filter(slug=course_name_slug)[0]
		context_dict['course'] = course
	except Course.DoesNotExist:
		context_dict['course'] = None
	return render(request, 'WOF/course_base.html', context=context_dict)

@login_required
def add_course(request):
	course_created = False
	course = None
	if request.method == "POST":
		if not (StudentUser.objects.filter(user=request.user)[0].isAdmin):
			return error(request, "Must be an admin to add a course")
		course_form = CourseForm(request.POST)
		if course_form.is_valid():
			course = course_form.save()

			course_created = True
			# Make function to write to xml 
			writeCourseToXML(course.university.slug, 
						course.slug, 
						request.POST.get('courseDescription'))

		else:
			print(course_form.errors)
	else:
		if not (StudentUser.objects.filter(user=request.user)[0].isAdmin):
			return error(request, "Must be an admin to add a course")
		course_form = CourseForm()
	return render(request, 'WOF/add_course.html', context={'course_form' : course_form,
															'course_created' : course_created,
															'course' : course})

@login_required
def delete_course(request, course_name_slug):
	if StudentUser.objects.filter(user=request.user).exists():
		student_user = StudentUser.objects.filter(user=request.user)[0]
		if not (student_user.isAdmin):
			return error(request, "User is not an admin")
	if request.method == "POST" and Course.objects.filter(slug=course_name_slug).exists():
		course = Course.objects.filter(slug=course_name_slug)[0]
		name_of_deleted = course.name
		course.delete()
		return file_deleted(request, name_of_deleted)
	else:
		return error(request, f"Failed to delete course with slug {course_name_slug}")

@login_required
@csrf_exempt
def delete_university(request):
	if request.is_ajax and request.method == "POST":
		university_name_slug = request.POST.get('university_slug')
		if University.objects.filter(slug=university_name_slug).exists():
			uni_deleted = University.objects.filter(slug=university_name_slug)[0]
			name_of_deleted = uni_deleted.name
			uni_deleted.delete()
		else:
			error(request, "University not found")
	return profile(request)

@login_required
def add_university(request):
	university_created = False
	university = None
	if request.method == "POST":
		university_form = UniversityForm(request.POST)
		if university_form.is_valid() and StudentUser.objects.filter(user=request.user)[0].isAdmin:
			university = university_form.save()
			student_user = StudentUser.objects.filter(user=request.user)[0]

			# writeUniversityToXML
			writeUniversityToXML(university.slug)
			student_user.university = university
			student_user.uni_admin = university
			student_user.save()
			university_created = True
		else:
			error(request, str(university_form.errors))
	else:
		if not StudentUser.objects.filter(user=request.user)[0].isAdmin:
			return error(request,  "User must be an admin")
		university_form = UniversityForm()
	return render(request, 'WOF/add_university.html', context={'university_form' : university_form,
																'university_created' : university_created,
																'university' : university})
def show_university(request, university_name_slug):
	context_dict = {}
	if University.objects.filter(slug=university_name_slug).exists():
		university = University.objects.filter(slug=university_name_slug)[0]
		courses = list(Course.objects.filter(university=university))
		context_dict['university'] = university
		context_dict['courses'] = courses
		return render(request, 'WOF/university_base.html', context=context_dict)
	else:
		return error(request, f"University at: {university_name_slug} does not exist")

def get_course_info(request, course_name_slug):
	if request.is_ajax and request.method == "GET":
		WORK_DIR = os.getcwd()
		file = ET.parse(os.path.join(WORK_DIR, "static", "xml", "uni_course_info.xml"))
		university_elements = list(file.getroot())
		# All the university elements
		for university in university_elements:
			courses = list(university)
			# Each course for each university
			for course in courses:
				# If found correct course
				if (course.attrib.get('id') == course_name_slug):
					information = course.text
					return JsonResponse({ 'course_text' : information })
		return JsonResponse({})
	else:
		return JsonResponse({})


arrayNums = [x for x in range(1,13)]
months = ["January", "Febuary", "March", "April", "May", "June", 
		"July", "August", "September", "October", "November", "December"];

all_months = dict(zip(months, arrayNums))

# HELPER FUNCTION NOT VIEW
def find_days_in_month(month : int, year : int):
	monthNum = month
	nextMonthNum = (monthNum + 1) % 12
	nextMonth = int(arrayNums[nextMonthNum-1])
	nextYear = year if nextMonth != 1 else year + 1 
	return abs((datetime.datetime(nextYear, nextMonth, 1) - datetime.datetime(year, monthNum, 1)).days)

@csrf_exempt
def find_tasks_month(request):
	if request.is_ajax and request.method == "POST":
		if StudentUser.objects.filter(user=request.user).exists():
			student_user = StudentUser.objects.filter(user=request.user)[0]
			month = int(request.POST.get("month")) + 1
			year = int(request.POST.get("year"))
			# Finding time between each month
			daysInMonth = find_days_in_month(month, year)
			tasks = {}
			for i in range(1, daysInMonth+1):
				date = datetime.datetime(year, month, i)
				if Task.objects.filter(dueDate=date, studentUser = student_user).exists():
					tasks[i] = str(Task.objects.get(dueDate=date, studentUser = student_user))

			return JsonResponse({"tasks" : tasks})
		else:
			return JsonResponse({"tasks" : []})
	else:
		return error(request, "Error occurred while searching database")

def check_task_exists(task_name, dueDate):
	slug_name = slugify(task_name)+f"-{dueDate.year}-{dueDate.month}-{dueDate.day}"
	return (Task.objects.filter(slug=slug_name)).exists()

@csrf_exempt
def add_task(request):

freshmen_world/templates/WOF/account.html
{% extends 'WOF/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Account page!
{% endblock %}


{% block body_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/authentication.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/account.css' %}"/>
    <script type="text/javascript" src="{% static 'js/account.js' %}"></script>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet">
    {% if updated %}
        <p>Account updated!<br />
    {% endif %}

    {% if user.is_authenticated and uni_admin %}
        {% csrf_token %}
        <button type="submit" id="delete-university" onClick="submit_delete('{{ student_user_university.slug }}')">Delete {{ student_user_university.name }}</button>
    {% endif %}

    <form id="student_user_change_form" method="post" action="{% url 'WOF:profile' %}" enctype="multipart/form-data">
        <div class="authentication-input-div update-page-background">
            <p id="login-text"><strong>Update your account</strong></p>
            {% csrf_token %}
            {{ student_user_change_form.as_p }}
            {{ student_user_change_profile_form.as_p }}
            <input type="submit" name="submit" value="Update" />
        </div>
    </form>
{% endblock %}

freshmen_world/templates/WOF/add_course.html
{% extends 'WOF/base.html' %}
{% load staticfiles  %}

{% block title_block %}
	Add course page
{% endblock %}

{% block body_block %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/authentication.css' %}"/>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap">
	<form id="student_user_form" method="post" action="{% url 'WOF:add_course' %}" enctype="multipart/form-data">
		<div class="authentication-input-div">
			{% csrf_token %}
			<p class="authentication-text">Create a course!</p>
			{% if course_created %}
				<p class="authentication-text" id="smaller-text">Course created: {{ course.name }}</p><br />
			{% endif %}
			{{ course_form.as_p }}
			<p>
				<input type="text" name="courseDescription" required="" placeholder="Course Description" id="id_courseDescription">
			</p>
			<input type="submit" name="submit" value="Create course" />
		</div>
	</form>
{% endblock %}

freshmen_world/templates/WOF/add_university.html
{% extends 'WOF/base.html' %}
{% load staticfiles  %}

{% block title_block %}
	Add university page
{% endblock %}

{% block body_block %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/authentication.css' %}"/>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap">
	<form id="student_user_form" method="post" action="{% url 'WOF:add_university' %}" enctype="multipart/form-data">
		<div class="authentication-input-div">
			{% csrf_token %}
			<p class="authentication-text">Create a university!</p>
			{% if university_created %}
				<p class="authentication-text" id="smaller-text">University created: {{ university.name }}</p><br />
			{% endif %}
			{{ university_form.as_p }}
			<input type="submit" name="submit" value="Create university" />
		</div>
	</form>
{% endblock %}

freshmen_world/templates/WOF/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>

    <head lang="en">
        <meta charset="UTF-8" />
        <title>
            Freshmen World - 
            {% block title_block %}
                Still making progress!
            {% endblock %} 
        </title>
        <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico'%}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/base.js' %}"></script>
        <!-- <link rel="stylesheet" href="{% static 'css/reset.css' %}"> -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    </head>

    <body>
        {% block top_bar_block %}
            <ul class="nav justify-content-center top-bar-block">
                <li class="nav-item"><a class="nav-link" href="{% url 'WOF:index' %}">Homepage</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'WOF:task_manager' %}">Task Manager</a></li>
            <!-- Student, at university -->
            {% if user.is_authenticated and student_university %}
                <li class="nav-item">
                    <div class="dropdown-info">
                        <button class="button-dropdown nav-link" id="course-button">Courses</button>
                        <div class="university-content-container">
                        {% for course in university_courses %}
                                <a href="{% url 'WOF:show_course' course.slug %}">{{ course.name }}</a>
                        {% endfor %}
                        {% if is_admin and uni_admin %}
                            <a href="{% url 'WOF:add_course' %}">Add Course</a>
                        {% endif %}
                        </div>
                    </div>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'WOF:profile' %}">Profile ({{ user.username }})</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'WOF:logout' %}">Logout</a></li>
             <!-- Student, not at uni -->
            {% elif user.is_authenticated and not student_university %}
                <li class="nav-item">
                    <div class="dropdown-info">
                        <button class="button-dropdown nav-link" id="course-button">University</button>
                        <div class="university-content-container">
                        {% for university in universities %}
                                <a href="{% url 'WOF:show_university' university.slug %}">{{ university.name }}</a>
                        {% endfor %}
                        {% if is_admin %}
                            <a href="{% url 'WOF:add_university' %}">Add University</a>
                        {% endif %}
                        </div>
                    </div>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'WOF:profile' %}">Profile ({{ user.username }}) </a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'WOF:logout' %}">Logout</a></li>
            <!-- Not logged in  -->
            {% else %}
                <li class="nav-item">
                    <div class="dropdown-info">
                        <button class="button-dropdown nav-link" id="course-button">University</button>
                        <div class="university-content-container">
                        {% for university in universities %}
                                <a href="{% url 'WOF:show_university' university.slug %}">{{ university.name }}</a>
                        {% endfor %}
                        {% if is_admin %}
                            <a href="{% url 'WOF:add_university' %}">Add University</a>
                        {% endif %}
                        </div>
                    </div>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'WOF:user_login' %}">Login</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'WOF:user_register' %}">Register</a></li>
            {% endif %}
            </ul>
        {% endblock %}
            <div class="body-block">
                {% block body_block %}
                {% endblock %}
            </div>
        {% block bottom_bar_block %}
            <div class="clear"></div>
            <footer class="footer-bottom-page">
                <div class="footer-container">
                    <div class="footer-item left">
                        <!-- Contact us -->
                        <p><a href="mailto:wad2lab12d@gmail.com">Contact us</a></p>
                        <p><a href="{% url 'WOF:team' %}">Meet the team</a></p>
                        <!-- Meet the team -->
                    </div>
                    <div class="footer-item right">
                        <p>Powered by WAD2 Lab 12D</p>
                    </div>
                </div>
            </footer>
        {% endblock %}  
    </body>
</html>

freshmen_world/templates/WOF/course_base.html
{% extends 'WOF/base.html' %}
{% load staticfiles  %}

{% block title_block %}
	{{ course.name }}
{% endblock %}

{% block body_block %}
	<script type="text/javascript" src="{% static 'js/course_info.js' %}"></script>
	<link rel="stylesheet" href="{% static 'css/course_base.css' %}">
	<link rel="stylesheet" href="{% static 'css/flexgrid.css' %}">
	<div class="flex-grid course-base">
		<div class="col flex-grid-space flex-whole course-flex-space course-flex-background" id="course-name">
			<p id="course-name-content">{{ course.name }}</p>
		</div>
	</div>
	<div class="flex-grid course-base ">
		<div class="col flex-grid-space flex-thirds course-flex-background" id="course-description">
			<p id="xml-content">Check the most recent information!
			<button type="button" id="content-button">See content</button></p><br />
		</div>
		<div class="col flex-grid-space flex-thirds course-flex-background" id="course-info">
			<p id="course-credits"> Credits: {{ course.credits }} </p>
			<p id="course-level"> Course Level: {{ course.level }} </p>
		</div>
		<div class="col flex-grid-space flex-thirds course-flex-background" id="course-head">
			{{ course.courseConvener }}
			{{ course.courseNumber }}
		</div>
	</div>
	{% if user.is_authenticated and uni_admin %}
		<form action="{% url 'WOF:delete_course' course.slug %}" method="POST">
			{% csrf_token %}
			<button type="submit" id="delete-button">Delete course</button>
		</form>	
	{% endif %}
{% endblock %}

freshmen_world/templates/WOF/deleted_file.html
{% extends 'WOF/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Deleted files page
{% endblock %}

{% block body_block %}
	<link rel="stylesheet" href="{% static 'css/small_page.css' %}" />
	<p id="small_message"> File deleted: <br /> 
		{{ file_deleted }}
	</p>
{% endblock %}

freshmen_world/templates/WOF/error_page.html
{% extends 'WOF/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Error page
{% endblock %}

{% block body_block %}
	<link rel="stylesheet" href="{% static 'css/small_age.css' %}" />
	<p id="small_message"> Error occured: <br /> 
		{{ error }}
	</p>
{% endblock %}

freshmen_world/templates/WOF/team_members.html
{% extends 'WOF/base.html' %}
{% load staticfiles %}


{% block title_block %}
    Team Members page!
{% endblock %}


{% block body_block %}
    <link rel="stylesheet" href="{% static 'css/flexgrid.css' %}">
    <div class="flex-grid">
        <div class="col flex-grid-space flex-thirds"><img src="{% static 'images/sam_image.png' %}"></div>
        <div class="col flex-grid-space flex-thirds"><img src="{% static 'images/tianrun_image.png' %}"></div>
        <div class="col flex-grid-space flex-thirds"><img src="{% static 'images/zhiang_image.png' %}"></div>
    </div>
    <div class="flex-grid">
        <div class="col flex-grid-space flex-half"><img src="{% static 'images/robert_image.png' %}"></div>
        <div class="col flex-grid-space flex-half"><img src="{% static 'images/laurie_image.png' %}"></div>
    </div>
{% endblock %}

freshmen_world/templates/WOF/user_login.html
{% extends 'WOF/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login Page
{% endblock %}

{% block body_block %}
    <link rel="stylesheet" href="{% static 'css/authentication.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet">
    <form id="login_form" method="post" action="{% url 'WOF:user_login' %}">
        <div class="authentication-input-div">
            {% csrf_token %}
            <p class="authentication-text">Login to your account!</p>
            <p class="p-login"><input type="text" name="username" value="" size="40" placeholder="Username" /></p> <br />
            <p class="p-login"><input type="password" name="password" value="" size="20" placeholder="Password" /></p><br />
            <p class="p-login"><input type="submit" value="Submit" /></p>
        </div>
    </form>
{% endblock %}

freshmen_world/templates/WOF/user_register.html
{% extends 'WOF/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Register page
{% endblock %}

{% block body_block %}
	<script type="text/javascript" src="{% static 'js/authentication.js' %}"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/authentication.css' %}"/>
	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet">
	{% if registered %}
		<p>Thank you for joining us<br />
		<a href="{% url 'WOF:index' %}">Return to the homepage</a></p><br />
		
	{% else %}
		<form id="student_user_form" method="post" action="{% url 'WOF:user_register' %}" enctype="multipart/form-data">
			<div class="authentication-input-div">
				<p class="authentication-text">Register at Freshmen World!</p>
				{% csrf_token %}
				{{ student_user_form.as_p }}
				{{ student_user_profile_form.as_p }}
				<input type="submit" name="submit" value="Register" />
			</div>
		</form>
	{% endif %}
{% endblock%}